pipeline {
    agent any

    stages {

        stage('Debug') {
            steps {
                bat 'cd'
                bat 'dir'
            }
        }

        stage('Debug Project Folder') {
            steps {
                dir('project-4-sqlite-notes-app') {
                    bat 'cd'
                    bat 'dir'
                }
            }
        }
    }
}