pipeline {
    agent any

    stages {

        stage('Build Docker Image') {
            steps {
                dir('project-4-sqlite-notes-app') {
                    bat 'docker build -t sqlite-notes-app .'
                }
            }
        }

        stage('Stop Old Container') {
            steps {
                bat 'docker stop sqlite-notes-app-container || exit 0'
                bat 'docker rm sqlite-notes-app-container || exit 0'
            }
        }

        stage('Run New Container') {
            steps {
                bat 'docker run -d -p 5000:5000 --name sqlite-notes-app-container sqlite-notes-app'
            }
        }
    }
}