pipeline{
    agent any
    stages{
        stage('Build Docker Image'){
             steps{
                bat 'docker build -t sqlite-notes-app .'
                // Add Docker build commands here
            }
        }
        stage('Stop Old Container'){
            steps{
               bat 'docker stop sqlite-notes-app-container || exit 0'
               bat 'docker rm sqlite-notes-app-container || exit 0'
                // Add stop commands here
            }
        }
        stage('Run New Container'){
            steps{
                bat 'docker run -d -p 5000:5000 --name sqlite-notes-app-container sqlite-notes-app'
                // Add run commands here

       
            }
        }
    }
}